import Skeleton from '@mui/material/Skeleton';
import Stack from '@mui/material/Stack';

import {
  OrderNumberDescription,
  DtDdWrap,
  BtnWrap,
  AllProductWrap,
  ProductWrap,
  ImgWrap,
  TotalPriceWrap,
  ProductDlWrap,
  OrderInfoWrap,
  DeliveryInfo,
  UserInfo,
  DeleveryReq,
  Menu,
} from './styled';

export const OrderDetailLoading = () => {
  return (
    <>
      <OrderNumberDescription>
        <DtDdWrap>
          <div style={{ width: '100%' }}>
            <div>
              <Skeleton
                variant="text"
                animation="wave"
                width="10%"
                height="100%"
              />
              <Skeleton
                variant="text"
                animation="wave"
                width="30%"
                height="100%"
              />
            </div>
            <div>
              <Skeleton
                variant="text"
                animation="wave"
                width="10%"
                height="100%"
              />
              <Skeleton
                variant="text"
                animation="wave"
                width="30%"
                height="100%"
              />
            </div>
          </div>
          <div>
            <button type="button" className="orderstatus">
              <Stack spacing={1} style={{ width: '6rem', height: '100%' }}>
                <Skeleton
                  variant="text"
                  animation="wave"
                  width="100%"
                  height="100%"
                />
              </Stack>
            </button>
          </div>
        </DtDdWrap>
        <BtnWrap style={{ height: '4rem' }}>
          <Skeleton
            variant="text"
            animation="wave"
            width="100%"
            height="100%"
            style={{ marginRight: '1rem' }}
          />
          <Skeleton
            variant="text"
            animation="wave"
            width="100%"
            height="100%"
          />
        </BtnWrap>
      </OrderNumberDescription>
      <Menu>
        <Stack spacing={1} style={{ width: '100%', height: '100%' }}>
          <Skeleton
            style={{ marginRight: '1rem' }}
            variant="text"
            animation="wave"
            width="100%"
            height="100%"
          />
          <Skeleton variant="text" animation="wave" width="40%" height="100%" />
        </Stack>
      </Menu>
      <AllProductWrap>
        <ProductWrap>
          <ImgWrap>
            <Stack spacing={1} style={{ width: '100%', height: '100%' }}>
              <Skeleton
                variant="rectangular"
                animation="wave"
                width="100%"
                height="100%"
              />
            </Stack>
          </ImgWrap>
          <ProductDlWrap>
            <Skeleton
              variant="text"
              animation="wave"
              width="25%"
              height="100%"
            />
            <Skeleton
              variant="text"
              animation="wave"
              width="25%"
              height="100%"
            />
            <Skeleton
              variant="text"
              animation="wave"
              width="25%"
              height="100%"
            />
            <Skeleton
              variant="text"
              animation="wave"
              width="25%"
              height="100%"
              className="loading_dd"
            />
          </ProductDlWrap>
        </ProductWrap>
      </AllProductWrap>
      <TotalPriceWrap>
        <div className="mobile-Only shipping">
          <Skeleton variant="text" animation="wave" width="30%" height="100%" />
        </div>
        <div className="totalPrice">
          <div className="mobile-Only" style={{ width: '10%', height: '100%' }}>
            <Skeleton
              variant="text"
              animation="wave"
              width="100%"
              height="100%"
            />
          </div>
          <div
            className="realtotalPrice"
            style={{ width: '10%', height: '100%' }}
          >
            <Skeleton
              variant="text"
              animation="wave"
              width="100%"
              height="100%"
            />
          </div>
        </div>
      </TotalPriceWrap>
      <OrderInfoWrap>
        <DeliveryInfo>
          <h2>
            <Skeleton
              variant="text"
              animation="wave"
              width="25%"
              height="100%"
            />
          </h2>
          <div>
            <div>
              <Skeleton
                variant="text"
                animation="wave"
                width="20%"
                height="100%"
              />
            </div>
            <div>
              <Skeleton
                variant="text"
                animation="wave"
                width="20%"
                height="100%"
              />
            </div>
            <div>
              <Skeleton
                variant="text"
                animation="wave"
                width="20%"
                height="100%"
              />
            </div>
          </div>
        </DeliveryInfo>
        <UserInfo>
          <h2>
            <Skeleton
              variant="text"
              animation="wave"
              width="25%"
              height="100%"
            />
          </h2>
          <div>
            <div>
              <dt>
                <Skeleton
                  variant="text"
                  animation="wave"
                  width="25%"
                  height="100%"
                />
              </dt>
              <dd>
                <Skeleton
                  variant="text"
                  animation="wave"
                  width="25%"
                  height="100%"
                />
              </dd>
            </div>
            <div>
              <dt>
                <Skeleton
                  variant="text"
                  animation="wave"
                  width="25%"
                  height="100%"
                />
              </dt>
              <dd>
                <Skeleton
                  variant="text"
                  animation="wave"
                  width="25%"
                  height="100%"
                />
              </dd>
            </div>
            <div>
              <dt>
                <Skeleton
                  variant="text"
                  animation="wave"
                  width="25%"
                  height="100%"
                />
              </dt>
              <dd>
                <Skeleton
                  variant="text"
                  animation="wave"
                  width="25%"
                  height="100%"
                />
              </dd>
            </div>
            <div>
              <dt>
                <Skeleton
                  variant="text"
                  animation="wave"
                  width="25%"
                  height="100%"
                />
              </dt>
              <dd>
                <Skeleton
                  variant="text"
                  animation="wave"
                  width="25%"
                  height="100%"
                />
              </dd>
            </div>
          </div>
        </UserInfo>
        <DeleveryReq>
          <h2>
            <Skeleton
              variant="text"
              animation="wave"
              width="25%"
              height="100%"
            />
          </h2>
          <div>
            <div>
              <dt>
                <Skeleton
                  variant="text"
                  animation="wave"
                  width="25%"
                  height="100%"
                />
              </dt>
              <dd>
                <Skeleton
                  variant="text"
                  animation="wave"
                  width="25%"
                  height="100%"
                />
              </dd>
            </div>
            <div>
              <dt>
                <Skeleton
                  variant="text"
                  animation="wave"
                  width="25%"
                  height="100%"
                />
              </dt>
              <dd>
                <Skeleton
                  variant="text"
                  animation="wave"
                  width="25%"
                  height="100%"
                />
              </dd>
            </div>
          </div>
        </DeleveryReq>
      </OrderInfoWrap>
    </>
  );
};
