name: deploy-to-s3-example

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: git clone
        uses: actions/checkout@v2

      - name: npm install for eslint
        run: npm install

      - name: npm install
        run: npm install
        working-directory: ./client

      - name: build
        run: CI='' npm run build
        working-directory: ./client

      - name: deploy
        working-directory: ./client
        env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
        dependencies: build
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            dist s3://www.lumieregallery.site
